### PR TITLE
Make _authenticate_default_user public

### PR DESCRIPTION
**Pull request by timaa2k**
I'd like to use the `_authenticate_default_user_public` in the resilience tests.
@adamtheturtle strongly suggested to not call private Python methods, therefore I now would like to make it a public method. If there are any objections against this please comment here.

### CODE REVIEW

**Comment by adamtheturtle** [comment]
Initial thought that maybe I'll think through when it is not near EOD Friday:

Is this really `authenticate` or is it `login` (as per @jgehrcke 's precise definitions)? If it is `login` let's change the name of the function before making it public.

**Comment by jgehrcke** [comment]
> Is this really authenticate or is it login (as per @jgehrcke 's precise definitions)? If it is login let's change the name of the function before making it public.

:heart: 

It is login :-)

**Comment by adamtheturtle** [comment]
> as per @jgehrcke 's precise definitions

I mean https://jira.mesosphere.com/browse/QUALITY-1856?focusedCommentId=149722&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-149722.

**Comment by adamtheturtle** [comment]
> @adamtheturtle strongly suggested to not call private Python methods

FWIW it is exactly PRs like this one - with 0 consideration for users of the private method `_authenticate_default_user_public` - that make that policy a useful one 😄 

Please change this method's name / docstring and logging to use "login" and include as much of the definition of "login" as you think is sensible.

Otherwise, well, the CI is broken but that seems unrelated.

**Comment by timaa2k** [comment]
Adressed @adamtheturtle comments. I don't know what's going on with the CI.

**Comment by adamtheturtle** [comment]
Thank you @timaa2k and @jgehrcke .

I'm happy now, but this needs a DC/OS Test Utils maintainer to say that they are happy to maintain this interface.

**Comment by mellenburg** [comment]
Also, its worth nothing that the integration tests didn't fail, but rather the *delete* of the cluster by *dcos-launch* did, so this PR is blameless in that regard

**Comment by margaret** [comment]
The failures in the integration tests were https://jira.mesosphere.com/browse/QUALITY-1963 😞 which is unrelated to this PR, but the tests all passed, so I am merging it.

**Comment by margaret** [comment]
I made an issue for finessing the retry here https://jira.mesosphere.com/browse/QUALITY-2091

**Pull request merged**
