### PR TITLE
Port over part of DCOS-41819 PR

### PR DESCRIPTION
**Pull request by br-lewis**
## High-level description

This increases the wait time for a diagnostics bundle from 2 minutes to 20 minutes.
Corresponding PR that this will partially replace: https://github.com/dcos/dcos/pull/3952

## Corresponding DC/OS tickets (obligatory)

These JIRA ticket(s) must be updated (ideally closed) in the moment this PR lands:

  - [DCOS-41819](https://github.com/dcos/dcos/pull/3952) 

## Related `dcos-launch` and `dcos` PRs

Is this change going to be propagated up into another repo? Test the change by bumping the `dcos-test-utils` SHA to point to these changes to test it. Link the corresponding PRs here:

## Checklist for all PRs

  - [X] Included a test which will fail if code is reverted but test is not. If there is no test please explain here: Increases a timeout
  - [X] Include a test in `dcos-integration-tests` in https://github.com/dcos/dcos or explain why this is not applicable: Increases a timeout in code used from there
  - [X] Include a test in https://github.com/dcos/dcos-launch or explain why this is not applicable: Not a change to a test condition

[Integration tests](https://teamcity.mesosphere.io/project.html?projectId=DcosIo_DcosTestUtils) were run and

  - [ ] Integration Test - Enterprise (link to job: )
  - [ ] Integration Test - Open (link to job: )

**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS LINE**

## Instructions and review process

**What is the review process and when will my changes land?**

All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).

Reviewers should be:
* Developers who understand the code being modified.
* Developers responsible for code that interacts with or depends on the code being modified.

It is best to proactively ask for 2 reviews by @mentioning the candidate reviewers in the PR comments area. The responsibility is on the developer submitting the PR to follow-up with reviewers and make sure a PR is reviewed in a timely manner.

### CODE REVIEW

**Comment by br-lewis** [comment]
@adamtheturtle can you review?

**Comment by adamtheturtle** [comment]
I do not have authority to merge this PR. I would merge it if I could!

**Comment by br-lewis** [comment]
@cprovencher it looks like you have the ability to merge in this repo. Can you review or merge this please?

**Comment by orsenthil** [comment]
> Looks like the previous stop max delay was a mistake.

I read it opposite. I think, it is okay to increase to higher value. But not really sure about it's relation with the bug we are observing. Worth trying.

**Pull request merged**
